### ISSUE TITLE
mahadevsawale to-do list

### ISSUE THREAD

**Issue by mahadevsawale** [scatrin/sep-22-developers#6]
## To Do List

 - [x] Create an issue
 - [x] Create a branch
 - [x] Create file locally and push it
 - [x] Edit files GitHub.com and pull it
 - [ ] Create a pull request
 - [ ] Merge a pull request
 - [ ] Have a good time??

:+1:
